added owsap scanning

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -93,15 +93,32 @@ pipeline {
                         # ====== Collect the report ======
                         mkdir -p reports
                         mv zap_report.html reports/
+
+                    # ===== Quality Gate: fail build if FAIL-NEW > 0 =====
+                    FAIL_COUNT=$(grep -oE "FAIL-NEW: [0-9]+" reports/zap_report.html | awk '{print $2}')
+                    if [ -z "$FAIL_COUNT" ]; then
+                        FAIL_COUNT=0
+                    fi
+
+                    if [ "$FAIL_COUNT" -gt 0 ]; then
+                        echo "❌ ZAP found $FAIL_COUNT high severity vulnerabilities!"
+                        exit 1
+                    else
+                        echo "✅ No high severity vulnerabilities found. Proceeding..."
+                    fi
                     '''
                 }
-            }
-            post {
+                post {
                 always {
                     archiveArtifacts artifacts: 'reports/zap_report.html', fingerprint: true
                 }
+                success {
+                    echo '✅ ZAP scan completed successfully — no critical vulnerabilities.'
+                }
+                failure {
+                    echo '❌ Build failed due to critical ZAP findings.'
+                }
             }
-        }
     }
 
     post {
