handling the exit code

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -35,8 +35,7 @@ pipeline {
 
                     echo "🔍 Running Gitleaks scan..."
                     set +e  # temporarily disable fail-fast
-                    gitleaks detect --source . --no-git --verbose --report-path gitleaks-report.json
-                    result=$?  # capture exit status
+                    gitleaks detect --source .  --verbose --report-path gitleaks-report.json result=$?  # capture exit status
                     set -e  # re-enable fail-fast
 
                 if [ "$result" -ne 0 ]; then
